### ISSUE TITLE
In der Schnellnavigation ein "Gehe zu Heute" Link

### ISSUE THREAD

**Issue by olien** [eaCe/rex_calendar#14]

**Comment by eaCe** [comment]
Was soll dann passieren?
Direkt Edit/Add funktion aufrufen?

**Comment by olien** [comment]
Nein. Wenn ich eine von heute abweichende Anzeige ausgewählt habe springe ich einfach auf die Monats / Jahr Ansicht die "heute" beinhaltet

**Comment by eaCe** [comment]
Ah achso, alles klar, wird gemacht
