### ISSUE TITLE
Structured Data Markup für events + JSON-LD-Ausgabe

### ISSUE THREAD

**Issue by alexplusde** [eaCe/rex_calendar#18]
Ich verwende bei Terminen / Events möglichst noch Structured Data Markup, um diese für Google zugänglich zu machen. Entsprechend wäre es klasse, wenn die üblichen Pflichtfelder im Kalender zu Terminen verfügbar wären, bspw. Location oder Price.

https://developers.google.com/search/docs/guides/intro-structured-data
https://schema.org/Event
https://search.google.com/structured-data/testing-tool

JSON-LD-Beispiel (aktuelle Empfehlung von Google)

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "Example Band goes to San Francisco",
  "startDate" : "2013-09-14T21:30",
  "url" : "http://example.com/tourdates.html",
  "location" : {
    "@type" : "Place",
    "sameAs" : "http://www.hi-dive.com",
    "name" : "The Hi-Dive",
    "address" : "7 S. Broadway, Denver, CO 80209"
  }
}
</script>

```

Ergebnis:

![image](https://cloud.githubusercontent.com/assets/3855487/16484342/04655d36-3eb9-11e6-9423-1943a823e050.png)

**Comment by eaCe** [comment]
@alexplusde ist es dafür notwendig Daten wie die Adresse zur verfügung zu stellen?
Wenn ja sollte das Global passieren oder für jeden Eintrag extra?

**Comment by alexplusde** [comment]
um die Angaben vollständig zu machen, muss die Adresse an den Termin geknüpft sein. Diese kann ja, je nach Termin, unterschiedlich sein. Es gibt ja noch 1000 andere Felder für den Datentyp "event", aber Location ist schon mit das wichtigste, weil es sicherlich bei der lokalen Suche berücksichtigt wird.
